name: mlflow_env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip<=24.2
  - pip:
     - pandas
     - scikit-learn
     - matplotlib
     - seaborn
     - mlflow
     - google-api-python-client
     - google-auth
     - google-auth-oauthlib
     - google-auth-httplib2